import type { Metadata } from "next";
import { PT_Sans, PT_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Yasma Login",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
        {children}
      </>
  );
}
